# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Introduction
    url: introduction
    weight: 100
  - parent: Introduction
    name: About ME
    url: /author/김수민/
    weight: 110
  - parent: Introduction
    name: History
    url: introduction
    weight: 120


  - name: Education
    url: lectures
    weight: 200
  - parent: Education
    name: Lectures Taken
    url: lectures
    weight: 210
  - parent: Education
    name: Programming Languages
    url: event
    weight: 220


  - name: Activities
    url: project
    weight: 300
  - parent: Activities
    name: Projects
    url: project
    weight: 310
  - parent: Activities
    name: School Clubs
    url: schoolclubs
    weight: 320


  - name: Future Plans
    url: post
    weight: 600
  - parent: Future Plans
    name: Job-Related
    url: notification
    weight: 610
  - parent: Future Plans
    name: Not Job-Related
    url: post
    weight: 620


  - name: Contact
    url: contact
    weight: 700
  - parent: Contact
    name: About LOGO
    url: publication
    weight: 710
  - parent: Contact
    name: How to Contact
    url: contact
    weight: 720
